#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-sqlite3
Version  : 1.3.10
Release  : 1
URL      : https://rubygems.org/downloads/sqlite3-1.3.10.gem
Source0  : https://rubygems.org/downloads/sqlite3-1.3.10.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: rubygem-sqlite3-lib
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : sqlite-autoconf-dev

%description
= SQLite3/Ruby Interface
* https://github.com/sparklemotion/sqlite3-ruby
* http://groups.google.com/group/sqlite3-ruby

%package lib
Summary: lib components for the rubygem-sqlite3 package.
Group: Libraries

%description lib
lib components for the rubygem-sqlite3 package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n sqlite3-1.3.10
gem spec %{SOURCE0} -l --ruby > rubygem-sqlite3.gemspec

%build
gem build rubygem-sqlite3.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
sqlite3-1.3.10.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/sqlite3-1.3.10.gem
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/RbConfig/cdesc-RbConfig.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/AbortException/cdesc-AbortException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/AuthorizationException/cdesc-AuthorizationException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Backup/cdesc-Backup.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Backup/finish-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Backup/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Backup/pagecount-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Backup/remaining-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Backup/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Blob/cdesc-Blob.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/BusyException/cdesc-BusyException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/CantOpenException/cdesc-CantOpenException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Constants/ColumnType/cdesc-ColumnType.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Constants/ErrorCode/cdesc-ErrorCode.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Constants/TextRep/cdesc-TextRep.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Constants/cdesc-Constants.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ConstraintException/cdesc-ConstraintException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/CorruptException/cdesc-CorruptException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/authorizer%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/authorizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/busy_handler-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/busy_timeout%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/busy_timeout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/cdesc-Database.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/closed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/collation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/collations-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/complete%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/create_aggregate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/create_function-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/define_aggregator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/define_function-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/enable_load_extension-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/encoding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/errcode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/errmsg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/execute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/execute2-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/execute_batch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/finalize-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/finalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/get_first_row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/get_first_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/interrupt-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/last_insert_row_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/load_extension-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/open-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/prepare-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/quote-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/results_as_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/step-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/total_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/trace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/transaction_active%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Database/translator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/EmptyException/cdesc-EmptyException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Exception/cdesc-Exception.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Exception/code-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Exception/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/FormatException/cdesc-FormatException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/FullException/cdesc-FullException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/FunctionProxy/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/FunctionProxy/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/FunctionProxy/cdesc-FunctionProxy.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/FunctionProxy/count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/FunctionProxy/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/FunctionProxy/result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/FunctionProxy/set_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/IOException/cdesc-IOException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/InternalException/cdesc-InternalException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/InterruptException/cdesc-InterruptException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/LockedException/cdesc-LockedException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/MemoryException/cdesc-MemoryException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/MismatchException/cdesc-MismatchException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/MisuseException/cdesc-MisuseException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/NotADatabaseException/cdesc-NotADatabaseException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/NotFoundException/cdesc-NotFoundException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/PermissionException/cdesc-PermissionException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/auto_vacuum%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/auto_vacuum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/cache_size%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/cache_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/cdesc-Pragmas.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/database_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/default_cache_size%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/default_cache_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/default_synchronous%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/default_synchronous-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/default_temp_store%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/default_temp_store-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/foreign_key_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/full_column_names%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/full_column_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/get_boolean_pragma-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/get_enum_pragma-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/get_int_pragma-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/get_query_pragma-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/index_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/index_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/integrity_check-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/parser_trace%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/parser_trace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/schema_cookie%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/schema_cookie-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/set_boolean_pragma-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/set_enum_pragma-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/set_int_pragma-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/synchronous%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/synchronous-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/table_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/temp_store%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/temp_store-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/tweak_default-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/user_cookie%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/user_cookie-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/vdbe_trace%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/vdbe_trace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Pragmas/version_compare-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ProtocolException/cdesc-ProtocolException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/RangeException/cdesc-RangeException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ReadOnlyException/cdesc-ReadOnlyException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/ArrayWithTypes/cdesc-ArrayWithTypes.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/ArrayWithTypesAndFields/cdesc-ArrayWithTypesAndFields.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/HashWithTypesAndFields/cdesc-HashWithTypesAndFields.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/cdesc-ResultSet.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/closed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/columns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/each_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/eof%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/next-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/next_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ResultSet/types-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/SQLException/cdesc-SQLException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/SchemaChangedException/cdesc-SchemaChangedException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/active%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/bind_param-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/bind_parameter_count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/bind_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/cdesc-Statement.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/clear_bindings%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/closed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/column_count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/column_decltype-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/column_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/columns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/database_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/done%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/execute%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/execute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/get_metadata-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/remainder-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/reset%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Statement/types-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/TooBigException/cdesc-TooBigException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Translator/add_translator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Translator/cdesc-Translator.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Translator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Translator/register_default_translators-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Translator/translate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Translator/type_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/UnsupportedException/cdesc-UnsupportedException.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/cdesc-Value.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/handle-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/null%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/to_blob-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/to_f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/to_i-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/to_int64-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/Value/type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/VersionProxy/cdesc-VersionProxy.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/cdesc-SQLite3.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/commit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/create_aggregate_handler-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/finalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/instance-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/libversion-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/ordered_map_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/readonly%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/rollback-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/SQLite3/transaction-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/String/to_blob-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/ext/sqlite3/page-Makefile.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/page-API_CHANGES_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/page-CHANGELOG_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/sqlite3-1.3.10/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/sqlite3-1.3.10/gem.build_complete
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/sqlite3-1.3.10/gem_make.out
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/sqlite3-1.3.10/mkmf.log
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/.gemtest
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/API_CHANGES.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/CHANGELOG.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ChangeLog.cvs
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/.RUBYARCHDIR.-.sqlite3.time
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/backup.c
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/backup.h
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/backup.o
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/database.c
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/database.h
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/database.o
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/exception.c
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/exception.h
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/exception.o
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/extconf.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/sqlite3.c
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/sqlite3.o
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/sqlite3_ruby.h
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/statement.c
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/statement.h
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/statement.o
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/faq/faq.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/faq/faq.yml
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/constants.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/database.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/pragmas.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/resultset.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/statement.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/translator.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/value.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/setup.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/tasks/faq.rake
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/tasks/gem.rake
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/tasks/native.rake
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/tasks/vendor_sqlite3.rake
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_backup.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_collation.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_database.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_database_readonly.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_deprecated.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_encoding.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_integration.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_integration_open_close.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_integration_pending.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_integration_resultset.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_integration_statement.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_result_set.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_sqlite3.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_statement.rb
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/test/test_statement_execute.rb
/usr/lib64/ruby/gems/2.2.0/specifications/sqlite3-1.3.10.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/sqlite3-1.3.10/sqlite3/sqlite3_native.so
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/ext/sqlite3/sqlite3_native.so
/usr/lib64/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/sqlite3_native.so
